### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by wDvy** [speedacm/GameDevSHMUP#32]
Test issue to demonstrate issue functionality in GitHub

**Comment by CollinDewey** [comment]
Bruh

**Comment by wDvy** [comment]
@LegitMagic bruh

**Comment by CollinDewey** [comment]
> @LegitMagic bruh
> 

@wDvy bruh

**Comment by wDvy** [comment]
making a tutorial rn
also currently at work lmao

**Comment by CollinDewey** [comment]
> making a tutorial rn
> also currently at work lmao
> 

Nice! I should be able to make most meeting this semester.

**Comment by wDvy** [comment]
_sickkk_
