### ISSUE TITLE
Consistent File Names

### ISSUE THREAD

**Issue by CollinDewey** [speedacm/GameDevSHMUP#44]
Currently the file names across our resources are of various types. We have

PascalCase
With Spaces
With_Underscores
lowercase

We need to pick some sort of consistent file naming scheme.

**Comment by wDvy** [comment]
or camelCase 😈

**Comment by CollinDewey** [comment]
No actually, there aren't any files in camelCase.

I was listing what existed, not potential naming schemes.

**Comment by wDvy** [comment]
I see, I'll probably go with underscores since spaces cause issues
